name: Build Project
on: [push]
jobs:
  Build:
    strategy:
        fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build react
      run: npm run build