name: Build Project react
on: [push]
jobs:
  Build:
    strategy:
        fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install modules
      run: npm install

    - name: Build react
      run: npm run build